import java.util.ArrayList;
import java.util.List;

public class CarData {
    public static List<Car> getPredefinedCars() {
        List<Car> cars = new ArrayList<>();
        cars.add(new Car.CarBuilder(1, "Toyota", "Camry 55")
                .year(2017)
                .bodyType("Sedan")
                .color("Black")
                .engineVolume(3.5)
                .gearboxType("Automatic")
                .description("The car is in perfect condition.")
                .price(15600000 )
                .sellerPhone("+77053122084")
                .vinCode("VIN000001")
                .build());

        cars.add(new Car.CarBuilder(2, "Toyota", "Hilux ")
                .year(2024)
                .bodyType("Pickup")
                .color("Black")
                .engineVolume(2.7)
                .gearboxType("Mechanics")
                .description("All-wheel drive")
                .price(21500000)
                .sellerPhone("+77076280537")
                .vinCode("VIN000002")
                .build());

        cars.add(new Car.CarBuilder(3, "BMW ", "X7 ")
                .year(2024 )
                .bodyType("Crossover")
                .color("Black metallic")
                .engineVolume(3.0)
                .gearboxType("Automatic")
                .description("Fuel-efficient and reliable")
                .price(79193000)
                .sellerPhone("+77075767172")
                .vinCode("VIN000003")
                .build());

        cars.add(new Car.CarBuilder(4, "Hyundai", "Tucson ")
                .year(2015)
                .bodyType("Crossover")
                .color("brown metallic")
                .engineVolume(2.0)
                .gearboxType("Automatic")
                .description("Spacious and powerful")
                .price(8590000)
                .sellerPhone("+77751397220")
                .vinCode("VIN000004")
                .build());

        cars.add(new Car.CarBuilder(5, "Hyundai ", "Accent ")
                .year(2019)
                .bodyType("Sedan")
                .color("white")
                .engineVolume(1.6)
                .gearboxType("Automatic")
                .description("Full package")
                .price(7190000)
                .sellerPhone("+77763193001")
                .vinCode("VIN000005")
                .build());

        cars.add(new Car.CarBuilder(6, "Hyundai ", "Elantra ")
                .year(2016)
                .bodyType("Sedan")
                .color("White")
                .engineVolume(1.5)
                .gearboxType("Variator")
                .description("Spacious and powerful")
                .price(8999000)
                .sellerPhone("+77785089752")
                .vinCode("VIN000006")
                .build());

        cars.add(new Car.CarBuilder(7, "Lexus ", "LX 570 ")
                .year(2013)
                .bodyType("SUV")
                .color("white")
                .engineVolume(5.7)
                .gearboxType("Automatic")
                .description("Full package")
                .price(27000000)
                .sellerPhone("+77076280537")
                .vinCode("VIN000007")
                .build());

        cars.add(new Car.CarBuilder(8, "Toyota", "Corolla")
                .year(2021)
                .bodyType("Sedan")
                .color("White")
                .engineVolume(1.6)
                .gearboxType("Automatic")
                .description("Front wheel drive")
                .price(10500000)
                .sellerPhone("+77019731818")
                .vinCode("VIN000008")
                .build());

        cars.add(new Car.CarBuilder(9, "Mercedes-Benz", "E 350")
                .year(2019)
                .bodyType("Sedan")
                .color("Black")
                .engineVolume(1.5)
                .gearboxType("Manual")
                .description("Fuel-efficient and reliable")
                .price(7105000)
                .sellerPhone("+77781625252")
                .vinCode("VIN000009")
                .build());

        cars.add(new Car.CarBuilder(10, "Lexus", "RX 350")
                .year(2023 )
                .bodyType("Crossover")
                .color("Black metallic")
                .engineVolume(2.4)
                .gearboxType("Automatic")
                .description("Spacious and powerful")
                .price(43000000)
                .sellerPhone("+77014016527")
                .vinCode("VIN000010")
                .build());

        cars.add(new Car.CarBuilder(11, "Toyota ", "Land Cruiser Prado")
                .year(2008 )
                .bodyType("SUV")
                .color("White")
                .engineVolume(4.0)
                .gearboxType("Manual")
                .description("Fuel-efficient and reliable")
                .price(7595000)
                .sellerPhone("+77761143438")
                .vinCode("VIN000011")
                .build());

        cars.add(new Car.CarBuilder(12, "Lexus ", "LX 470")
                .year(2004)
                .bodyType("SUV")
                .color("White")
                .engineVolume(4.7)
                .gearboxType("Automatic")
                .description("All-wheel drive")
                .price(11500000)
                .sellerPhone("+7071000011")
                .vinCode("VIN000012")
                .build());

        cars.add(new Car.CarBuilder(13, "Mercedes-Benz", "E 230")
                .year(1992)
                .bodyType("Sedan")
                .color("golden")
                .engineVolume(2.3)
                .gearboxType("Mechanics")
                .description("Rear wheel drive")
                .price(2000000)
                .sellerPhone("+77018943566")
                .vinCode("VIN000013")
                .build());

        cars.add(new Car.CarBuilder(14, "Lexus", "ES 250")
                .year(2022)
                .bodyType("Sedan")
                .color("black")
                .engineVolume(2.5)
                .gearboxType("Automatic")
                .description("Spacious and powerful")
                .price(28750000)
                .sellerPhone("+77780254372")
                .vinCode("VIN000014")
                .build());

        cars.add(new Car.CarBuilder(15, "Toyota ", "Camry ")
                .year(2021 )
                .bodyType("Sedan")
                .color("brown metallic")
                .engineVolume(2.5)
                .gearboxType("Automatic")
                .description("Fuel-efficient and reliable")
                .price(14000000)
                .sellerPhone("+77015401224")
                .vinCode("VIN000015")
                .build());

        cars.add(new Car.CarBuilder(16, "JAC ", "S3 Pro")
                .year(2024 )
                .bodyType("Crossover")
                .color("black")
                .engineVolume(1.6)
                .gearboxType("Automatic")
                .description("Front wheel drive")
                .price(10000000)
                .sellerPhone("+77770055005")
                .vinCode("VIN000016")
                .build());

        cars.add(new Car.CarBuilder(17, "Kia", "Sportage Classic")
                .year(2024 )
                .bodyType("Crossover")
                .color("White")
                .engineVolume(2.0)
                .gearboxType("Automatic")
                .description("Fuel-efficient and reliable")
                .price(13890000)
                .sellerPhone("+7 7470951925")
                .vinCode("VIN000017")
                .build());

        cars.add(new Car.CarBuilder(18, "Jetour ", "T2 Adventure")
                .year(2024)
                .bodyType("SUV")
                .color("grey")
                .engineVolume(2.0)
                .gearboxType("Robot")
                .description("Spacious and powerful")
                .price(15490000)
                .sellerPhone("+77717007717")
                .vinCode("VIN000018")
                .build());

        cars.add(new Car.CarBuilder(19, "Honda", "Model19")
                .year(2016)
                .bodyType("Sedan")
                .color("Black")
                .engineVolume(2.0)
                .gearboxType("Manual")
                .description("Fuel-efficient and reliable")
                .price(9555000)
                .sellerPhone("+7071000018")
                .vinCode("VIN000019")
                .build());

        cars.add(new Car.CarBuilder(20, "Mercedes-Benz", "E 400")
                .year(2013 )
                .bodyType("Sedan")
                .color("White metallic")
                .engineVolume(3.0)
                .gearboxType("Automatic")
                .description("All-wheel drive")
                .price(15900000)
                .sellerPhone("+77712222228")
                .vinCode("VIN000020")
                .build());

        cars.add(new Car.CarBuilder(21, "VAZ (Lada)", "Granta 2190")
                .year(2018)
                .bodyType("Sedan")
                .color("white")
                .engineVolume(1.6)
                .gearboxType("Automatic")
                .description("Fuel-efficient and reliable")
                .price(3380000)
                .sellerPhone("+77787492036")
                .vinCode("VIN000021")
                .build());

        cars.add(new Car.CarBuilder(22, "Hyundai ", "Sonata ")
                .year(2021 )
                .bodyType("Sedan")
                .color("grey")
                .engineVolume(2.0)
                .gearboxType("Machine")
                .description("Spacious and powerful")
                .price(10810000)
                .sellerPhone("+7 701 004 6267")
                .vinCode("VIN000022")
                .build());

        cars.add(new Car.CarBuilder(23, "Hyundai ", "Accent ")
                .year(2021 )
                .bodyType("Sedan")
                .color("white")
                .engineVolume(1.6)
                .gearboxType("Manual")
                .description("Fuel-efficient and reliable")
                .price(7100000)
                .sellerPhone("+77010046236")
                .vinCode("VIN000023")
                .build());

        cars.add(new Car.CarBuilder(24, "Lexus ", "RX 330")
                .year(2004)
                .bodyType("Crossover")
                .color("silver metallic")
                .engineVolume(3.3)
                .gearboxType("Automatic")
                .description("All-wheel drive")
                .price(9100000)
                .sellerPhone("+77772066626")
                .vinCode("VIN000024")
                .build());

        cars.add(new Car.CarBuilder(25, "Toyota ", "RAV4")
                .year(2019 )
                .bodyType("Crossover")
                .color("White")
                .engineVolume(2.0)
                .gearboxType("Manual")
                .description("Fuel-efficient and reliable")
                .price(14990000)
                .sellerPhone("+77273131505")
                .vinCode("VIN000025")
                .build());

        cars.add(new Car.CarBuilder(26, "Lexus ", "RX 300")
                .year(2005)
                .bodyType("Crossover")
                .color("Silver metallic")
                .engineVolume(2.5)
                .gearboxType("Automatic")
                .description("Front wheel drive")
                .price(7700000)
                .sellerPhone("+77754790404")
                .vinCode("VIN000026")
                .build());

        cars.add(new Car.CarBuilder(27, "Toyota ", "Model27")
                .year(2021 )
                .bodyType("Crossover")
                .color("blue metallic")
                .engineVolume(2.5)
                .gearboxType("Automatic")
                .description("full package")
                .price(25500000)
                .sellerPhone("+77769933909")
                .vinCode("VIN000027")
                .build());

        cars.add(new Car.CarBuilder(28, "Toyota", "Model28")
                .year(2012)
                .bodyType("SUV")
                .color("White")
                .engineVolume(2.0)
                .gearboxType("Automatic")
                .description("Spacious and powerful")
                .price(11760000)
                .sellerPhone("+7071000027")
                .vinCode("VIN000028")
                .build());

        cars.add(new Car.CarBuilder(29, "Hyundai ", "Santa Fe")
                .year(2019 )
                .bodyType("Crossover")
                .color("Blue")
                .engineVolume(2.4)
                .gearboxType("Manual")
                .description("All-wheel drive")
                .price(13440000)
                .sellerPhone("+77010046195")
                .vinCode("VIN000029")
                .build());

        cars.add(new Car.CarBuilder(30, "Toyota", "Model30")
                .year(2014)
                .bodyType("SUV")
                .color("White")
                .engineVolume(1.5)
                .gearboxType("Automatic")
                .description("Spacious and powerful")
                .price(12250000)
                .sellerPhone("+7071000029")
                .vinCode("VIN000030")
                .build());

        cars.add(new Car.CarBuilder(31, "Mercedes-Benz", "E 55 AMG")
                .year(2004 )
                .bodyType("Sedan")
                .color("white")
                .engineVolume(5.5 )
                .gearboxType("Automatic")
                .description("Rear wheel drive")
                .price(13000000)
                .sellerPhone("+77760418844")
                .vinCode("VIN000031")
                .build());

        cars.add(new Car.CarBuilder(32, "Lexus", "ES 250")
                .year(2015)
                .bodyType("Sedan")
                .color("Black metallic")
                .engineVolume(2.5)
                .gearboxType("Automatic")
                .description("Front wheel drive")
                .price(12800000 )
                .sellerPhone("+77053156692")
                .vinCode("VIN000032")
                .build());

        cars.add(new Car.CarBuilder(33, "Toyota ", "Sienna ")
                .year(2017)
                .bodyType("Minivan")
                .color("white")
                .engineVolume(3.5)
                .gearboxType("Automatic")
                .description("Fuel-efficient and reliable")
                .price(15250000)
                .sellerPhone("+77016748987")
                .vinCode("VIN000033")
                .build());

        cars.add(new Car.CarBuilder(34, "Kia ", "K5 ")
                .year(2024)
                .bodyType("Sedan")
                .color("White")
                .engineVolume(2.0)
                .gearboxType("Automatic")
                .description("Full package")
                .price(17300000)
                .sellerPhone("+77479213687")
                .vinCode("VIN000034")
                .build());

        cars.add(new Car.CarBuilder(35, "Hyundai ", "Bayon ")
                .year(2023 )
                .bodyType("Crossover")
                .color("blue")
                .engineVolume(1.4)
                .gearboxType("Manual")
                .description("Front wheel drive")
                .price(9290000)
                .sellerPhone("+77787491609")
                .vinCode("VIN000035")
                .build());

        cars.add(new Car.CarBuilder(36, "Mercedes-Benz ", "E 200")
                .year(2016 )
                .bodyType("Sedan")
                .color("green")
                .engineVolume(2.0)
                .gearboxType("Automatic")
                .description("Rear wheel drive")
                .price(19500000)
                .sellerPhone("+77064142000")
                .vinCode("VIN000036")
                .build());

        cars.add(new Car.CarBuilder(37, "Lexus ", "LS 460")
                .year(2007 )
                .bodyType("Sedan")
                .color("silver metallic")
                .engineVolume(4.6)
                .gearboxType("Manual")
                .description("Rear wheel drive")
                .price(6500000)
                .sellerPhone("+77077669363")
                .vinCode("VIN000037")
                .build());

        cars.add(new Car.CarBuilder(38, "Toyota", "Carina E ")
                .year(1992 )
                .bodyType("Sedan")
                .color("burgundy")
                .engineVolume(2.0)
                .gearboxType("Automatic")
                .description("Spacious and powerful")
                .price(2000000)
                .sellerPhone("+77780089909")
                .vinCode("VIN000038")
                .build());

        cars.add(new Car.CarBuilder(39, "Kia ", "Sorento ")
                .year(2022)
                .bodyType("Crossover")
                .color("white")
                .engineVolume(3.5)
                .gearboxType("Automatic")
                .description("Front wheel drive")
                .price(20500000)
                .sellerPhone("+77068414433")
                .vinCode("VIN000039")
                .build());

        cars.add(new Car.CarBuilder(40, "Mercedes-Benz", "ML 63 AMG")
                .year(2012)
                .bodyType("SUV")
                .color("White")
                .engineVolume(5.5 )
                .gearboxType("Automatic")
                .description("Spacious and powerful")
                .price(22000000)
                .sellerPhone("+77018080022")
                .vinCode("VIN000040")
                .build());

        cars.add(new Car.CarBuilder(41, "Lexus", "RX 500h")
                .year(2024 )
                .bodyType("Crossover")
                .color("Black")
                .engineVolume(2.4)
                .gearboxType("Automatic")
                .description("full package")
                .price(49800000)
                .sellerPhone("+77719200083")
                .vinCode("VIN000041")
                .build());

        cars.add(new Car.CarBuilder(42, "Kia ", "Optima ")
                .year(2018)
                .bodyType("Sedan")
                .color("White")
                .engineVolume(2.4)
                .gearboxType("Automatic")
                .description("Front wheel drive")
                .price(7700000)
                .sellerPhone("+77004149700")
                .vinCode("VIN000042")
                .build());

        cars.add(new Car.CarBuilder(43, "Honda", "Model43")
                .year(2014)
                .bodyType("Sedan")
                .color("Black")
                .engineVolume(2.0)
                .gearboxType("Manual")
                .description("Fuel-efficient and reliable")
                .price(15435000)
                .sellerPhone("+77004149700")
                .vinCode("VIN000043")
                .build());

        cars.add(new Car.CarBuilder(44, "Daewoo ", "Matiz ")
                .year(2014 )
                .bodyType("Hatchback")
                .color("red")
                .engineVolume(0.8)
                .gearboxType("Automatic")
                .description("Front wheel drive")
                .price(1930000)
                .sellerPhone("+77787491586")
                .vinCode("VIN000044")
                .build());

        cars.add(new Car.CarBuilder(45, "Volkswagen ", "Polo ")
                .year(2016)
                .bodyType("Sedan")
                .color("blue")
                .engineVolume(1.6)
                .gearboxType("Manual")
                .description("Front wheel drive")
                .price(5680000)
                .sellerPhone("+77787492052")
                .vinCode("VIN000045")
                .build());

        cars.add(new Car.CarBuilder(46, "Kia ", "K7 ")
                .year(2020)
                .bodyType("Sedan")
                .color("Blue metallic")
                .engineVolume(2.5)
                .gearboxType("Automatic")
                .description("full package")
                .price(13500000)
                .sellerPhone("+77085219863")
                .vinCode("VIN000046")
                .build());

        cars.add(new Car.CarBuilder(47, "Kia ", "Rio ")
                .year(2004 )
                .bodyType("Station wagon")
                .color("green")
                .engineVolume(1.5)
                .gearboxType("Automatic")
                .description("Front wheel drive")
                .price(1700000)
                .sellerPhone("+77013477599")
                .vinCode("VIN000047")
                .build());

        cars.add(new Car.CarBuilder(48, "VAZ (Lada)", "2114 ")
                .year(2013)
                .bodyType("Hatchback")
                .color("White")
                .engineVolume(1.6)
                .gearboxType("Automatic")
                .description("Spacious and powerful")
                .price(1120000)
                .sellerPhone("+77787492484")
                .vinCode("VIN000048")
                .build());

        cars.add(new Car.CarBuilder(49, "Mercedes-Benz ", "ML 350")
                .year(2010)
                .bodyType("SUV")
                .color("Black metallic")
                .engineVolume(3.5)
                .gearboxType("Mechanics")
                .description("Fuel-efficient and reliable")
                .price(9800000)
                .sellerPhone("+77027772380")
                .vinCode("VIN000049")
                .build());

        cars.add(new Car.CarBuilder(50, "VAZ (Lada)", "Priora 2170")
                .year(2013)
                .bodyType("Sedan")
                .color("White")
                .engineVolume(1.6)
                .gearboxType("Automatic")
                .description("All-wheel drive")
                .price(1840000)
                .sellerPhone("+77787492402")
                .vinCode("VIN000050")
                .build());

        cars.add(new Car.CarBuilder(51, "Audi ", "A5")
                .year(2023)
                .bodyType("Liftback")
                .color("red")
                .engineVolume(2.0)
                .gearboxType("Robot")
                .description("Front wheel drive")
                .price(18000000)
                .sellerPhone("+77771815357")
                .vinCode("VIN000051")
                .build());

        cars.add(new Car.CarBuilder(52, "Mercedes-Benz", "A 200")
                .year(2013 )
                .bodyType("Hatchback")
                .color("White metallic")
                .engineVolume(1.6)
                .gearboxType("Automatic")
                .description("Spacious and powerful")
                .price(7500000)
                .sellerPhone("+77011911444")
                .vinCode("VIN000052")
                .build());

        cars.add(new Car.CarBuilder(53, "Kia ", "Cerato ")
                .year(2023 )
                .bodyType("Sedan")
                .color("Black")
                .engineVolume(2.0)
                .gearboxType("Automatic")
                .description("full package")
                .price(10900000)
                .sellerPhone("+77014070737")
                .vinCode("VIN000053")
                .build());

        cars.add(new Car.CarBuilder(54, "Chery ", "Tiggo 7 Pro Prestige")
                .year(2024 )
                .bodyType("Crossover")
                .color("White")
                .engineVolume(1.5)
                .gearboxType("Automatic")
                .description("Front wheel drive")
                .price(9790000)
                .sellerPhone("+77473404040")
                .vinCode("VIN000054")
                .build());

        cars.add(new Car.CarBuilder(55, "Chevrolet ", "Cobalt ")
                .year(2022)
                .bodyType("Sedan")
                .color("metallic grey")
                .engineVolume(1.5)
                .gearboxType("Manual")
                .description("100% better")
                .price(6400000)
                .sellerPhone("+77779844030")
                .vinCode("VIN000055")
                .build());

        cars.add(new Car.CarBuilder(56, "Chevrolet ", "Nexia ")
                .year(2022 )
                .bodyType("Sedan")
                .color("White")
                .engineVolume(1.5)
                .gearboxType("Automatic")
                .description("Front wheel drive")
                .price(5320000)
                .sellerPhone("+77787491568")
                .vinCode("VIN000056")
                .build());

        cars.add(new Car.CarBuilder(57, "Kia ", "Cerato ")
                .year(2023 )
                .bodyType("Sedan")
                .color("Black")
                .engineVolume(2.0)
                .gearboxType("Mechanics")
                .description("Front wheel drive")
                .price(11500000)
                .sellerPhone("+77781612616")
                .vinCode("VIN000057")
                .build());

        cars.add(new Car.CarBuilder(58, "Mercedes-Benz", "G 63 AMG")
                .year(2020 )
                .bodyType("SUV")
                .color("White metallic")
                .engineVolume(4.0)
                .gearboxType("Automatic")
                .description("All-wheel drive")
                .price(102000000)
                .sellerPhone("+77778914571")
                .vinCode("VIN000058")
                .build());

        cars.add(new Car.CarBuilder(59, "Mercedes-Benz", "G 63 AMG")
                .year(2016 )
                .bodyType("SUV")
                .color("Grey")
                .engineVolume(5.5)
                .gearboxType("Mechanics")
                .description("Fuel-efficient and reliable")
                .price(45000000)
                .sellerPhone("+77772257077")
                .vinCode("VIN000059")
                .build());

        cars.add(new Car.CarBuilder(60, "Toyota", "Camry 70")
                .year(2018)
                .bodyType("Sedan")
                .color("White metallic")
                .engineVolume(2.5)
                .gearboxType("Automatic")
                .description("Spacious and powerful")
                .price(14000000)
                .sellerPhone("+77017775632")
                .vinCode("VIN000060")
                .build());
        return cars;
    }
}
