import java.util.ArrayList;
import java.util.List;

public class CarData {
    public static List<Car> getPredefinedCars() {
        List<Car> cars = new ArrayList<>();
        cars.add(new Car.CarBuilder(1, "Honda", "Model1")
                .year(2011)
                .bodyType("Sedan")
                .color("Black")
                .engineVolume(2.0)
                .gearboxType("Manual")
                .description("Fuel-efficient and reliable")
                .price(10500)
                .sellerPhone("+123456789")
                .vinCode("VIN000001")
                .build());

        cars.add(new Car.CarBuilder(2, "Toyota", "Model2")
                .year(2012)
                .bodyType("SUV")
                .color("White")
                .engineVolume(2.5)
                .gearboxType("Automatic")
                .description("Spacious and powerful")
                .price(11000)
                .sellerPhone("+123456789")
                .vinCode("VIN000002")
                .build());

        cars.add(new Car.CarBuilder(3, "Honda", "Model3")
                .year(2013)
                .bodyType("Sedan")
                .color("Black")
                .engineVolume(1.5)
                .gearboxType("Manual")
                .description("Fuel-efficient and reliable")
                .price(11500)
                .sellerPhone("+123456789")
                .vinCode("VIN000003")
                .build());

        cars.add(new Car.CarBuilder(4, "Toyota", "Model4")
                .year(2014)
                .bodyType("SUV")
                .color("White")
                .engineVolume(2.0)
                .gearboxType("Automatic")
                .description("Spacious and powerful")
                .price(12000)
                .sellerPhone("+123456789")
                .vinCode("VIN000004")
                .build());

        cars.add(new Car.CarBuilder(5, "Honda", "Model5")
                .year(2015)
                .bodyType("Sedan")
                .color("Black")
                .engineVolume(2.5)
                .gearboxType("Manual")
                .description("Fuel-efficient and reliable")
                .price(12500)
                .sellerPhone("+123456789")
                .vinCode("VIN000005")
                .build());

        cars.add(new Car.CarBuilder(6, "Toyota", "Model6")
                .year(2016)
                .bodyType("SUV")
                .color("White")
                .engineVolume(1.5)
                .gearboxType("Automatic")
                .description("Spacious and powerful")
                .price(13000)
                .sellerPhone("+123456789")
                .vinCode("VIN000006")
                .build());

        cars.add(new Car.CarBuilder(7, "Honda", "Model7")
                .year(2017)
                .bodyType("Sedan")
                .color("Black")
                .engineVolume(2.0)
                .gearboxType("Manual")
                .description("Fuel-efficient and reliable")
                .price(13500)
                .sellerPhone("+123456789")
                .vinCode("VIN000007")
                .build());

        cars.add(new Car.CarBuilder(8, "Toyota", "Model8")
                .year(2018)
                .bodyType("SUV")
                .color("White")
                .engineVolume(2.5)
                .gearboxType("Automatic")
                .description("Spacious and powerful")
                .price(14000)
                .sellerPhone("+123456789")
                .vinCode("VIN000008")
                .build());

        cars.add(new Car.CarBuilder(9, "Honda", "Model9")
                .year(2019)
                .bodyType("Sedan")
                .color("Black")
                .engineVolume(1.5)
                .gearboxType("Manual")
                .description("Fuel-efficient and reliable")
                .price(14500)
                .sellerPhone("+123456789")
                .vinCode("VIN000009")
                .build());

        cars.add(new Car.CarBuilder(10, "Toyota", "Model10")
                .year(2020)
                .bodyType("SUV")
                .color("White")
                .engineVolume(2.0)
                .gearboxType("Automatic")
                .description("Spacious and powerful")
                .price(15000)
                .sellerPhone("+123456789")
                .vinCode("VIN000010")
                .build());

        cars.add(new Car.CarBuilder(11, "Honda", "Model11")
                .year(2021)
                .bodyType("Sedan")
                .color("Black")
                .engineVolume(2.5)
                .gearboxType("Manual")
                .description("Fuel-efficient and reliable")
                .price(15500)
                .sellerPhone("+123456789")
                .vinCode("VIN000011")
                .build());

        cars.add(new Car.CarBuilder(12, "Toyota", "Model12")
                .year(2022)
                .bodyType("SUV")
                .color("White")
                .engineVolume(1.5)
                .gearboxType("Automatic")
                .description("Spacious and powerful")
                .price(16000)
                .sellerPhone("+123456789")
                .vinCode("VIN000012")
                .build());

        cars.add(new Car.CarBuilder(13, "Honda", "Model13")
                .year(2010)
                .bodyType("Sedan")
                .color("Black")
                .engineVolume(2.0)
                .gearboxType("Manual")
                .description("Fuel-efficient and reliable")
                .price(16500)
                .sellerPhone("+123456789")
                .vinCode("VIN000013")
                .build());

        cars.add(new Car.CarBuilder(14, "Toyota", "Model14")
                .year(2011)
                .bodyType("SUV")
                .color("White")
                .engineVolume(2.5)
                .gearboxType("Automatic")
                .description("Spacious and powerful")
                .price(17000)
                .sellerPhone("+123456789")
                .vinCode("VIN000014")
                .build());

        cars.add(new Car.CarBuilder(15, "Honda", "Model15")
                .year(2012)
                .bodyType("Sedan")
                .color("Black")
                .engineVolume(1.5)
                .gearboxType("Manual")
                .description("Fuel-efficient and reliable")
                .price(17500)
                .sellerPhone("+123456789")
                .vinCode("VIN000015")
                .build());

        cars.add(new Car.CarBuilder(16, "Toyota", "Model16")
                .year(2013)
                .bodyType("SUV")
                .color("White")
                .engineVolume(2.0)
                .gearboxType("Automatic")
                .description("Spacious and powerful")
                .price(18000)
                .sellerPhone("+123456789")
                .vinCode("VIN000016")
                .build());

        cars.add(new Car.CarBuilder(17, "Honda", "Model17")
                .year(2014)
                .bodyType("Sedan")
                .color("Black")
                .engineVolume(2.5)
                .gearboxType("Manual")
                .description("Fuel-efficient and reliable")
                .price(18500)
                .sellerPhone("+123456789")
                .vinCode("VIN000017")
                .build());

        cars.add(new Car.CarBuilder(18, "Toyota", "Model18")
                .year(2015)
                .bodyType("SUV")
                .color("White")
                .engineVolume(1.5)
                .gearboxType("Automatic")
                .description("Spacious and powerful")
                .price(19000)
                .sellerPhone("+123456789")
                .vinCode("VIN000018")
                .build());

        cars.add(new Car.CarBuilder(19, "Honda", "Model19")
                .year(2016)
                .bodyType("Sedan")
                .color("Black")
                .engineVolume(2.0)
                .gearboxType("Manual")
                .description("Fuel-efficient and reliable")
                .price(19500)
                .sellerPhone("+123456789")
                .vinCode("VIN000019")
                .build());

        cars.add(new Car.CarBuilder(20, "Toyota", "Model20")
                .year(2017)
                .bodyType("SUV")
                .color("White")
                .engineVolume(2.5)
                .gearboxType("Automatic")
                .description("Spacious and powerful")
                .price(20000)
                .sellerPhone("+123456789")
                .vinCode("VIN000020")
                .build());

        cars.add(new Car.CarBuilder(21, "Honda", "Model21")
                .year(2018)
                .bodyType("Sedan")
                .color("Black")
                .engineVolume(1.5)
                .gearboxType("Manual")
                .description("Fuel-efficient and reliable")
                .price(20500)
                .sellerPhone("+123456789")
                .vinCode("VIN000021")
                .build());

        cars.add(new Car.CarBuilder(22, "Toyota", "Model22")
                .year(2019)
                .bodyType("SUV")
                .color("White")
                .engineVolume(2.0)
                .gearboxType("Automatic")
                .description("Spacious and powerful")
                .price(21000)
                .sellerPhone("+123456789")
                .vinCode("VIN000022")
                .build());

        cars.add(new Car.CarBuilder(23, "Honda", "Model23")
                .year(2020)
                .bodyType("Sedan")
                .color("Black")
                .engineVolume(2.5)
                .gearboxType("Manual")
                .description("Fuel-efficient and reliable")
                .price(21500)
                .sellerPhone("+123456789")
                .vinCode("VIN000023")
                .build());

        cars.add(new Car.CarBuilder(24, "Toyota", "Model24")
                .year(2021)
                .bodyType("SUV")
                .color("White")
                .engineVolume(1.5)
                .gearboxType("Automatic")
                .description("Spacious and powerful")
                .price(22000)
                .sellerPhone("+123456789")
                .vinCode("VIN000024")
                .build());

        cars.add(new Car.CarBuilder(25, "Honda", "Model25")
                .year(2022)
                .bodyType("Sedan")
                .color("Black")
                .engineVolume(2.0)
                .gearboxType("Manual")
                .description("Fuel-efficient and reliable")
                .price(22500)
                .sellerPhone("+123456789")
                .vinCode("VIN000025")
                .build());

        cars.add(new Car.CarBuilder(26, "Toyota", "Model26")
                .year(2010)
                .bodyType("SUV")
                .color("White")
                .engineVolume(2.5)
                .gearboxType("Automatic")
                .description("Spacious and powerful")
                .price(23000)
                .sellerPhone("+123456789")
                .vinCode("VIN000026")
                .build());

        cars.add(new Car.CarBuilder(27, "Honda", "Model27")
                .year(2011)
                .bodyType("Sedan")
                .color("Black")
                .engineVolume(1.5)
                .gearboxType("Manual")
                .description("Fuel-efficient and reliable")
                .price(23500)
                .sellerPhone("+123456789")
                .vinCode("VIN000027")
                .build());

        cars.add(new Car.CarBuilder(28, "Toyota", "Model28")
                .year(2012)
                .bodyType("SUV")
                .color("White")
                .engineVolume(2.0)
                .gearboxType("Automatic")
                .description("Spacious and powerful")
                .price(24000)
                .sellerPhone("+123456789")
                .vinCode("VIN000028")
                .build());

        cars.add(new Car.CarBuilder(29, "Honda", "Model29")
                .year(2013)
                .bodyType("Sedan")
                .color("Black")
                .engineVolume(2.5)
                .gearboxType("Manual")
                .description("Fuel-efficient and reliable")
                .price(24500)
                .sellerPhone("+123456789")
                .vinCode("VIN000029")
                .build());

        cars.add(new Car.CarBuilder(30, "Toyota", "Model30")
                .year(2014)
                .bodyType("SUV")
                .color("White")
                .engineVolume(1.5)
                .gearboxType("Automatic")
                .description("Spacious and powerful")
                .price(25000)
                .sellerPhone("+123456789")
                .vinCode("VIN000030")
                .build());

        cars.add(new Car.CarBuilder(31, "Honda", "Model31")
                .year(2015)
                .bodyType("Sedan")
                .color("Black")
                .engineVolume(2.0)
                .gearboxType("Manual")
                .description("Fuel-efficient and reliable")
                .price(25500)
                .sellerPhone("+123456789")
                .vinCode("VIN000031")
                .build());

        cars.add(new Car.CarBuilder(32, "Toyota", "Model32")
                .year(2016)
                .bodyType("SUV")
                .color("White")
                .engineVolume(2.5)
                .gearboxType("Automatic")
                .description("Spacious and powerful")
                .price(26000)
                .sellerPhone("+123456789")
                .vinCode("VIN000032")
                .build());

        cars.add(new Car.CarBuilder(33, "Honda", "Model33")
                .year(2017)
                .bodyType("Sedan")
                .color("Black")
                .engineVolume(1.5)
                .gearboxType("Manual")
                .description("Fuel-efficient and reliable")
                .price(26500)
                .sellerPhone("+123456789")
                .vinCode("VIN000033")
                .build());

        cars.add(new Car.CarBuilder(34, "Toyota", "Model34")
                .year(2018)
                .bodyType("SUV")
                .color("White")
                .engineVolume(2.0)
                .gearboxType("Automatic")
                .description("Spacious and powerful")
                .price(27000)
                .sellerPhone("+123456789")
                .vinCode("VIN000034")
                .build());

        cars.add(new Car.CarBuilder(35, "Honda", "Model35")
                .year(2019)
                .bodyType("Sedan")
                .color("Black")
                .engineVolume(2.5)
                .gearboxType("Manual")
                .description("Fuel-efficient and reliable")
                .price(27500)
                .sellerPhone("+123456789")
                .vinCode("VIN000035")
                .build());

        cars.add(new Car.CarBuilder(36, "Toyota", "Model36")
                .year(2020)
                .bodyType("SUV")
                .color("White")
                .engineVolume(1.5)
                .gearboxType("Automatic")
                .description("Spacious and powerful")
                .price(28000)
                .sellerPhone("+123456789")
                .vinCode("VIN000036")
                .build());

        cars.add(new Car.CarBuilder(37, "Honda", "Model37")
                .year(2021)
                .bodyType("Sedan")
                .color("Black")
                .engineVolume(2.0)
                .gearboxType("Manual")
                .description("Fuel-efficient and reliable")
                .price(28500)
                .sellerPhone("+123456789")
                .vinCode("VIN000037")
                .build());

        cars.add(new Car.CarBuilder(38, "Toyota", "Model38")
                .year(2022)
                .bodyType("SUV")
                .color("White")
                .engineVolume(2.5)
                .gearboxType("Automatic")
                .description("Spacious and powerful")
                .price(29000)
                .sellerPhone("+123456789")
                .vinCode("VIN000038")
                .build());

        cars.add(new Car.CarBuilder(39, "Honda", "Model39")
                .year(2010)
                .bodyType("Sedan")
                .color("Black")
                .engineVolume(1.5)
                .gearboxType("Manual")
                .description("Fuel-efficient and reliable")
                .price(29500)
                .sellerPhone("+123456789")
                .vinCode("VIN000039")
                .build());

        cars.add(new Car.CarBuilder(40, "Toyota", "Model40")
                .year(2011)
                .bodyType("SUV")
                .color("White")
                .engineVolume(2.0)
                .gearboxType("Automatic")
                .description("Spacious and powerful")
                .price(30000)
                .sellerPhone("+123456789")
                .vinCode("VIN000040")
                .build());

        cars.add(new Car.CarBuilder(41, "Honda", "Model41")
                .year(2012)
                .bodyType("Sedan")
                .color("Black")
                .engineVolume(2.5)
                .gearboxType("Manual")
                .description("Fuel-efficient and reliable")
                .price(30500)
                .sellerPhone("+123456789")
                .vinCode("VIN000041")
                .build());

        cars.add(new Car.CarBuilder(42, "Toyota", "Model42")
                .year(2013)
                .bodyType("SUV")
                .color("White")
                .engineVolume(1.5)
                .gearboxType("Automatic")
                .description("Spacious and powerful")
                .price(31000)
                .sellerPhone("+123456789")
                .vinCode("VIN000042")
                .build());

        cars.add(new Car.CarBuilder(43, "Honda", "Model43")
                .year(2014)
                .bodyType("Sedan")
                .color("Black")
                .engineVolume(2.0)
                .gearboxType("Manual")
                .description("Fuel-efficient and reliable")
                .price(31500)
                .sellerPhone("+123456789")
                .vinCode("VIN000043")
                .build());

        cars.add(new Car.CarBuilder(44, "Toyota", "Model44")
                .year(2015)
                .bodyType("SUV")
                .color("White")
                .engineVolume(2.5)
                .gearboxType("Automatic")
                .description("Spacious and powerful")
                .price(32000)
                .sellerPhone("+123456789")
                .vinCode("VIN000044")
                .build());

        cars.add(new Car.CarBuilder(45, "Honda", "Model45")
                .year(2016)
                .bodyType("Sedan")
                .color("Black")
                .engineVolume(1.5)
                .gearboxType("Manual")
                .description("Fuel-efficient and reliable")
                .price(32500)
                .sellerPhone("+123456789")
                .vinCode("VIN000045")
                .build());

        cars.add(new Car.CarBuilder(46, "Toyota", "Model46")
                .year(2017)
                .bodyType("SUV")
                .color("White")
                .engineVolume(2.0)
                .gearboxType("Automatic")
                .description("Spacious and powerful")
                .price(33000)
                .sellerPhone("+123456789")
                .vinCode("VIN000046")
                .build());

        cars.add(new Car.CarBuilder(47, "Honda", "Model47")
                .year(2018)
                .bodyType("Sedan")
                .color("Black")
                .engineVolume(2.5)
                .gearboxType("Manual")
                .description("Fuel-efficient and reliable")
                .price(33500)
                .sellerPhone("+123456789")
                .vinCode("VIN000047")
                .build());

        cars.add(new Car.CarBuilder(48, "Toyota", "Model48")
                .year(2019)
                .bodyType("SUV")
                .color("White")
                .engineVolume(1.5)
                .gearboxType("Automatic")
                .description("Spacious and powerful")
                .price(34000)
                .sellerPhone("+123456789")
                .vinCode("VIN000048")
                .build());

        cars.add(new Car.CarBuilder(49, "Honda", "Model49")
                .year(2020)
                .bodyType("Sedan")
                .color("Black")
                .engineVolume(2.0)
                .gearboxType("Manual")
                .description("Fuel-efficient and reliable")
                .price(34500)
                .sellerPhone("+123456789")
                .vinCode("VIN000049")
                .build());

        cars.add(new Car.CarBuilder(50, "Toyota", "Model50")
                .year(2021)
                .bodyType("SUV")
                .color("White")
                .engineVolume(2.5)
                .gearboxType("Automatic")
                .description("Spacious and powerful")
                .price(35000)
                .sellerPhone("+123456789")
                .vinCode("VIN000050")
                .build());

        cars.add(new Car.CarBuilder(51, "Honda", "Model51")
                .year(2022)
                .bodyType("Sedan")
                .color("Black")
                .engineVolume(1.5)
                .gearboxType("Manual")
                .description("Fuel-efficient and reliable")
                .price(35500)
                .sellerPhone("+123456789")
                .vinCode("VIN000051")
                .build());

        cars.add(new Car.CarBuilder(52, "Toyota", "Model52")
                .year(2010)
                .bodyType("SUV")
                .color("White")
                .engineVolume(2.0)
                .gearboxType("Automatic")
                .description("Spacious and powerful")
                .price(36000)
                .sellerPhone("+123456789")
                .vinCode("VIN000052")
                .build());

        cars.add(new Car.CarBuilder(53, "Honda", "Model53")
                .year(2011)
                .bodyType("Sedan")
                .color("Black")
                .engineVolume(2.5)
                .gearboxType("Manual")
                .description("Fuel-efficient and reliable")
                .price(36500)
                .sellerPhone("+123456789")
                .vinCode("VIN000053")
                .build());

        cars.add(new Car.CarBuilder(54, "Toyota", "Model54")
                .year(2012)
                .bodyType("SUV")
                .color("White")
                .engineVolume(1.5)
                .gearboxType("Automatic")
                .description("Spacious and powerful")
                .price(37000)
                .sellerPhone("+123456789")
                .vinCode("VIN000054")
                .build());

        cars.add(new Car.CarBuilder(55, "Honda", "Model55")
                .year(2013)
                .bodyType("Sedan")
                .color("Black")
                .engineVolume(2.0)
                .gearboxType("Manual")
                .description("Fuel-efficient and reliable")
                .price(37500)
                .sellerPhone("+123456789")
                .vinCode("VIN000055")
                .build());

        cars.add(new Car.CarBuilder(56, "Toyota", "Model56")
                .year(2014)
                .bodyType("SUV")
                .color("White")
                .engineVolume(2.5)
                .gearboxType("Automatic")
                .description("Spacious and powerful")
                .price(38000)
                .sellerPhone("+123456789")
                .vinCode("VIN000056")
                .build());

        cars.add(new Car.CarBuilder(57, "Honda", "Model57")
                .year(2015)
                .bodyType("Sedan")
                .color("Black")
                .engineVolume(1.5)
                .gearboxType("Manual")
                .description("Fuel-efficient and reliable")
                .price(38500)
                .sellerPhone("+123456789")
                .vinCode("VIN000057")
                .build());

        cars.add(new Car.CarBuilder(58, "Toyota", "Model58")
                .year(2016)
                .bodyType("SUV")
                .color("White")
                .engineVolume(2.0)
                .gearboxType("Automatic")
                .description("Spacious and powerful")
                .price(39000)
                .sellerPhone("+123456789")
                .vinCode("VIN000058")
                .build());

        cars.add(new Car.CarBuilder(59, "Honda", "Model59")
                .year(2017)
                .bodyType("Sedan")
                .color("Black")
                .engineVolume(2.5)
                .gearboxType("Manual")
                .description("Fuel-efficient and reliable")
                .price(39500)
                .sellerPhone("+123456789")
                .vinCode("VIN000059")
                .build());

        cars.add(new Car.CarBuilder(60, "Toyota", "Model60")
                .year(2018)
                .bodyType("SUV")
                .color("White")
                .engineVolume(1.5)
                .gearboxType("Automatic")
                .description("Spacious and powerful")
                .price(40000)
                .sellerPhone("+123456789")
                .vinCode("VIN000060")
                .build());
        return cars;
    }
}
